### ISSUE TITLE
Cannot use sample_qubo of BraketSampler with postprocessingType parameter

### ISSUE THREAD

**Issue by AoyuQC** [aws/amazon-braket-ocean-plugin-python#62]
**Describe the bug**
Cannot use the example from [tutorial](https://amazon-braket-ocean-plugin-python.readthedocs.io/en/latest/_apidoc/braket.ocean_plugin.braket_sampler.html) to test the sample_qubo function of BraketSampler

**To reproduce**
`from braket.ocean_plugin import BraketSampler`

`sampler = BraketSampler(s3_folder, "arn:aws:braket:::device/qpu/d-wave/Advantage_system4")`

`Q = {(0, 0): -1, (4, 4): -1, (0, 4): 2}`

`sampleset = sampler.sample_qubo(Q, postprocessingType="SAMPLING", shots=100)`

**Expected behavior**
Run without errors

**Screenshots or logs**
![Screen Shot 2021-11-29 at 3 19 20 PM](https://user-images.githubusercontent.com/4879237/143824962-457d85a2-cb10-4677-92f3-0c1ea7d2d4a8.png)

**System information**

A description of your system. Please provide:
- **Amazon Braket Python Ocean Plugin version**:1 .0.6
- **Amazon Braket Python SDK version**: 1.9.5.post0
- **Amazon Braket Python Schemas version**: 1.4.1
- **Python version**: 3.7.12

**Additional context**

**Comment by math411** [comment]
Hello,

Thank you for reaching out! For this issue and https://github.com/aws/amazon-braket-ocean-plugin-python/issues/63, a fix will be coming out shortly. 

In this particular case, the device specific properties for `arn:aws:braket:::device/qpu/d-wave/Advantage_system4` can be found [here](https://github.com/aws/amazon-braket-schemas-python/blob/main/src/braket/device_schema/dwave/dwave_advantage_device_level_parameters_v1.py). The other D-Wave device, `arn:aws:braket:::device/qpu/d-wave/DW_2000Q_6`, has device properties defined in a schema [here](https://github.com/aws/amazon-braket-schemas-python/blob/main/src/braket/device_schema/dwave/dwave_2000Q_device_level_parameters_v1.py#L29).

Feel free to respond with any further questions.

**Comment by math411** [comment]
A fix went out in https://github.com/aws/amazon-braket-ocean-plugin-python/pull/64 for this issue.
